name: Gradle Build & Test

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Generate dependency graph
      uses: gradle/actions/dependency-submission@v3
    - name: Execute Gradle build
      run: ./gradlew build --no-daemon
      env:
        TBA_API_KEY: ${{ secrets.TBA_API_KEY }}
